### ISSUE TITLE
Более предсказуемые типы данных из БД

### ISSUE THREAD

**Issue by riskul** [LetiLubov/statistic#3]
@LetiLubov @EvgeniiRay 

![image](https://user-images.githubusercontent.com/10918450/45590950-6866fb80-b94d-11e8-999e-6b6b363a147d.png)

Строчка номер с комментарием про BigDecimal как-то грустно выглядит.
Я бы возвращал более предсказуемые данные из БД. Раз уж вольность про intValue прошла. (:

**Comment by akelanova** [comment]
все изменилось)
